version: 2.0
config-version: 2
name: shop
profile: dbt2


model-paths:
  - "models"
  - "data"

target-path: "target"
   
vars:
  target_database: DBT
  target_schema: Public


models:
  shop:
    +materialized: table
